### ISSUE TITLE
Description- multi language support

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/cashondelivery-plugin-for-nopcommerce#1]
Now we can only write one language Description, but we have multi language store

See also: https://github.com/nopSolutions/nopCommerce/issues/3345

**Comment by TomasKoksch** [comment]
Hello, is it currently possible to make multilingual description in this plugin? Thx

**Comment by exileDev** [comment]
Done in bf94302fe70a180bf8768a4881291b6b1ae873df
