### ISSUE TITLE
 Cash on Delivery  - How to hide/deactivate Additional charges screen for End-User

### ISSUE THREAD

**Issue by alamricentre** [nopSolutions/cashondelivery-plugin-for-nopcommerce#3]
Hi Team,

I would request you to help us in this, when users are selecting the cash on delivery (COD) payment option then before going to the order confirmation screen one more additional screen is showing, we are not collecting any additional charges nor we want end-users to get confused or fed-up with many screen. 

Please guide us how we can disable/hide the additional screen  which is showing after selecting the cash on delivery option and before order confirmation screen. So that end-user will not go through many screens during check out.

Additional screen
https://drive.google.com/file/d/1h2NbaLqMzuvTxMKm4A5aAsF8u1Cx5vXC/view

Thanks in advance

**Comment by AndreiMaz** [comment]
It's possible with some minor customization.

But please use our forums for questions. This repository for work items only

**Comment by alamricentre** [comment]
Thank you for replying. 
Can you provide the Hide/show option in plugin itself, so that we can enable/disable (using check box) the additional screen.
