### ISSUE TITLE
COD  - Hide/deactivate Additional charges screen for End-User

### ISSUE THREAD

**Issue by alamricentre** [nopSolutions/cashondelivery-plugin-for-nopcommerce#4]
Can you provide the Hide/show option in plugin itself, so that admin can enable/disable (using check box) the additional screen.

**Comment by AndreiMaz** [comment]
What exactly do you mean? There is "additional fee" input on the configuration page. If you enter it, then end customers will see it

**Comment by alamricentre** [comment]
Even if not entering, it appears as additional page.   Step:2 screenshot refers the additional page. Which need to be an optional. Admin should have privileges to  hide/show this option to end-user.  

please check the screen shots 
step:1 https://drive.google.com/file/d/1losc9q51oKPC1DHCsohGoCFj06NKjJjQ/view
step: 2 https://drive.google.com/file/d/1z6PDFRb-O9loQ1AEHa8jTUsXBJ3Ffrs4/view
step:3  https://drive.google.com/file/d/1KKZDUH01Cw9N_HP16yGCupHQZ_X9Uye3/view

**Comment by AndreiMaz** [comment]
Just disable it - https://github.com/nopSolutions/cashondelivery-plugin-for-nopcommerce/blob/nop%D0%A1ommerce-4.50/Nop.Plugin.Payments.CashOnDelivery/Views/Configure.cshtml#L76
